#ifdef LANGUAGE_ENGLISH               // English language support (copy leading and trailing spaces when making your own language section)
  #define MOON_STRING "moon "
  #define SUN_STRING "sun "
  #define AZ_TARGET_STRING "Az Target "
  #define EL_TARGET_STRING "El Target "
  #define TARGET_STRING "Target "
  #define PARKING_STRING "Parking"
  #define PARKED_STRING "Parked"
  #define CW_STRING "CW"
  #define CCW_STRING "CCW"
  #define UP_STRING "UP"
  #define DOWN_STRING "DOWN"
  #define AZIMUTH_STRING "Azimuth "
  #define AZ_STRING "Az"
  #define AZ_SPACE_STRING "Az "
  #define ELEVATION_STRING "Elevation "
  #define SPACE_EL_STRING " El"
  #define SPACE_EL_SPACE_STRING " El "
  #define GPS_STRING "GPS"
  #define N_STRING "N"
  #define W_STRING "W"
  #define S_STRING "S"
  #define E_STRING "E"
  #define NW_STRING "NW"
  #define SW_STRING "SW"
  #define SE_STRING "SE"
  #define NE_STRING "NE"
  #define NNW_STRING "NNW"
  #define WNW_STRING "WNW"
  #define WSW_STRING "WSW"
  #define SSW_STRING "SSW"
  #define SSE_STRING "SSE"
  #define ESE_STRING "ESE"
  #define ENE_STRING "ENE"
  #define NNE_STRING "NNE"
#endif //LANGUAGE_ENGLISH